server:
  port: 443
  contextPath: /rest/v1
application:
  name: ${project.name}
  version: ${project.version}
  buildDate: ${buildDate}
oauth:
  issuer:
    algorithm: RS256
    keystore:
      url: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
    claims:
      aud: longball-7517e
      iss: https://securetoken.google.com/longball-7517e
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/longball
    username: postgres
server:
  port: 8411
---
spring:
  profiles: bypassToken
oauth:
  test:
    bypassToken: raspberries
