package net.alexanderkahn.longball.service.persistence.repository

import net.alexanderkahn.longball.service.persistence.model.PersistenceGameplayEvent

interface GameplayEventRepository: LongballRepository<PersistenceGameplayEvent>