package net.alexanderkahn.longball.service.persistence.repository

import net.alexanderkahn.longball.service.persistence.model.entity.PxPlateAppearanceResult

interface PlateAppearanceResultRepository : LongballRepository<PxPlateAppearanceResult>